# 디스코드 봇 관련 설정
# 만약 이 칸이 비어 있다면, 디스코드 봇은 작동하지 않습니다.

BOT_TOKEN: "여기에 디스코드 봇 토큰을 입력하세요. 본 프로그램은 토큰을 악용하지 않습니다."
CHANNEL_ID: "여기에 게임 진행 상황을 표시할 채널의 ID를 입력하세요. 본 프로그램은 채널 ID를 악용하지 않습니다."
ADMIN_CHANNEL_ID: "여기에 로그 등의 기능을 사용할 관리용 채널의 ID를 입력하세요. 본 프로그램은 채널 ID를 악용하지 않습니다."