name: Heracles
version: 1.0
main: kr.vanilage.main.Main
api-version: '1.21'

#libraries:
#  - org.jetbrains.kotlin:kotlin-stdlib:2.0.20
#  - net.dv8tion:JDA:5.1.0
#  - club.minnced:discord-webhooks:0.8.4
#  - io.ktor:ktor-server-core:3.0.0-rc-1
#  - io.ktor:ktor-server-netty:3.0.0-rc-1
#  - ch.qos.logback:logback-classic:1.4.14
